Repository pycontribs/wstools, pull requests merged in 2020-04, with the labels that each got.

#25 setup.py: Add six to install_requires (fixes #24)
  setup.py
Labels: packaging

#27 Fixed readme badges
  README.rst
Labels: docs

#28 travis maintenance
  .travis.yml
Labels: skip-changelog

#29 Other travis fixes
  .travis.yml
Labels: skip-changelog
